package middleware_test

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Arondy/url-shortener/internal/config"
	"github.com/Arondy/url-shortener/internal/core/transport/http/middleware"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

func newObservedLogger() (*zap.SugaredLogger, *observer.ObservedLogs) {
	core, logs := observer.New(zap.DebugLevel)
	return zap.New(core).Sugar(), logs
}

func TestWrapInMiddleware_GeneratesRequestID_AndOrdersMiddlewares(t *testing.T) {
	t.Parallel()
	logger, logs := newObservedLogger()

	var ctxID string
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id, ok := r.Context().Value(config.CtxKeyRequestID{}).(string)
		if !ok {
			t.Error("request ID is missing in handler context")
			return
		}
		ctxID = id
		w.WriteHeader(http.StatusOK)
	})

	req := httptest.NewRequest(http.MethodGet, "/devices", nil)
	w := httptest.NewRecorder()
	middleware.WrapInMiddleware(handler, logger).ServeHTTP(w, req)

	parsed, err := uuid.Parse(ctxID)
	require.NoError(t, err, "handler must receive a valid request ID")
	assert.Equal(t, uuid.Version(7), parsed.Version())

	entries := logs.All()
	require.NotEmpty(t, entries)
	sent := entries[len(entries)-1]
	assert.Equal(t, "sent response", sent.Message)

	fields := sent.ContextMap()
	assert.Equal(t, ctxID, fields["request_id"], "Logger must see the ID generated by RequestID (outermost)")
	assert.Equal(t, int64(http.StatusOK), fields["status_code"], "Trace must observe the status written by the handler")
}

func TestWrapInMiddleware_ReusesIncomingRequestID(t *testing.T) {
	t.Parallel()
	logger, _ := newObservedLogger()

	const incoming = "fixed-trace-id"
	var ctxID string
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id, _ := r.Context().Value(config.CtxKeyRequestID{}).(string)
		ctxID = id
	})

	req := httptest.NewRequest(http.MethodGet, "/devices", nil)
	req.Header.Set(config.RequestIDHeader, incoming)
	w := httptest.NewRecorder()
	middleware.WrapInMiddleware(handler, logger).ServeHTTP(w, req)

	assert.Equal(t, incoming, ctxID)
}

func TestWrapInMiddleware_Recover_Returns500OnPanic(t *testing.T) {
	t.Parallel()
	logger, _ := newObservedLogger()

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		panic("boom")
	})

	req := httptest.NewRequest(http.MethodPost, "/devices/checkin", nil)
	w := httptest.NewRecorder()
	middleware.WrapInMiddleware(handler, logger).ServeHTTP(w, req)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
}
